// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpOxLjadeiXe16-eq9qgLHk1x5Oat39-A',
    appId: '1:907201335916:web:0c1cc65ee1152bdae0fe49',
    messagingSenderId: '907201335916',
    projectId: 'project1-b3e69',
    authDomain: 'project1-b3e69.firebaseapp.com',
    storageBucket: 'project1-b3e69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkAPyjrH5oyNaBTwHW-J3OEzyBqFEXNVY',
    appId: '1:907201335916:android:8a48cb5134447fa4e0fe49',
    messagingSenderId: '907201335916',
    projectId: 'project1-b3e69',
    storageBucket: 'project1-b3e69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARYzSWZe3EYxI2RKXHWuI2O6BMPTwd0Ng',
    appId: '1:907201335916:ios:d5bb96d79c4ed6b4e0fe49',
    messagingSenderId: '907201335916',
    projectId: 'project1-b3e69',
    storageBucket: 'project1-b3e69.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARYzSWZe3EYxI2RKXHWuI2O6BMPTwd0Ng',
    appId: '1:907201335916:ios:d5bb96d79c4ed6b4e0fe49',
    messagingSenderId: '907201335916',
    projectId: 'project1-b3e69',
    storageBucket: 'project1-b3e69.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpOxLjadeiXe16-eq9qgLHk1x5Oat39-A',
    appId: '1:907201335916:web:9d0117636b1a5330e0fe49',
    messagingSenderId: '907201335916',
    projectId: 'project1-b3e69',
    authDomain: 'project1-b3e69.firebaseapp.com',
    storageBucket: 'project1-b3e69.appspot.com',
  );
}
